const photoList = [
    { id: 1, title: "Paysage Morocco", category: "Paysage", imageUrl: "imgSheep/img1.PNG", price: 3200, quality: "lower", type: "Essentials" },
    { id: 2, title: "Pub traditionnel", category: "Pub", imageUrl: "imgSheep/img2.PNG", price: 3500, quality: "lower", type: "Essentials" },
    { id: 3, title: "Maison typique", category: "Maison", imageUrl: "imgSheep/img3.PNG", price: 3700, quality: "lower", type: "Essentials" },
    { id: 4, title: "Cliffs of Moher", category: "Paysage", imageUrl: "imgSheep/img4.PNG", price: 3900, quality: "lower", type: "Essentials" },
    { id: 5, title: "Guinness Storehouse", category: "Pub", imageUrl: "imgSheep/img5.PNG", price: 4100, quality: "lower", type: "Essentials" },
    { id: 6, title: "Cottage Morocco", category: "Maison", imageUrl: "imgSheep/img6.PNG", price: 4300, quality: "lower", type: "Essentials" },
    { id: 7, title: "Désert marocain", category: "Paysage", imageUrl: "imgSheep/img7.PNG", price: 4500, quality: "lower", type: "Essentials" },
    { id: 8, title: "Bar local", category: "Pub", imageUrl: "imgSheep/img8.PNG", price: 4700, quality: "lower", type: "Essentials" },
    { id: 9, title: "Kasbah ancienne", category: "Maison", imageUrl: "imgSheep/img9.PNG", price: 4900, quality: "lower", type: "Essentials" },
    { id: 10, title: "Montagnes de l'Atlas", category: "Paysage", imageUrl: "imgSheep/img10.PNG", price: 5100, quality: "medium", type: "Essentials" },
    { id: 11, title: "Pub irlandais", category: "Pub", imageUrl: "imgSheep/img11.PNG", price: 5300, quality: "medium", type: "Essentials" },
    { id: 12, title: "Riad à Marrakech", category: "Maison", imageUrl: "imgSheep/img12.PNG", price: 5500, quality: "medium", type: "Essentials" },
    { id: 13, title: "Oasis verdoyante", category: "Paysage", imageUrl: "imgSheep/img13.PNG", price: 5700, quality: "medium", type: "Essentials" },
    { id: 14, title: "Pub vintage", category: "Pub", imageUrl: "imgSheep/img14.PNG", price: 5900, quality: "medium", type: "Essentials" },
    { id: 15, title: "Maison en pisé", category: "Maison", imageUrl: "imgSheep/img15.PNG", price: 6100, quality: "best", type: "Signature" },
    { id: 16, title: "Côte Atlantique", category: "Paysage", imageUrl: "imgSheep/img16.PNG", price: 6300, quality: "best", type: "Signature" },
    { id: 17, title: "Soirée au pub", category: "Pub", imageUrl: "imgSheep/img17.PNG", price: 6500, quality: "best", type: "Signature" },
    { id: 18, title: "Habitation rurale", category: "Maison", imageUrl: "imgSheep/img18.PNG", price: 6700, quality: "best", type: "Signature" },
    { id: 19, title: "Lever de soleil", category: "Paysage", imageUrl: "imgSheep/img19.PNG", price: 6900, quality: "best", type: "Signature" },
    { id: 20, title: "Pub à Essaouira", category: "Pub", imageUrl: "imgSheep/img20.PNG", price: 7000, quality: "best", type: "Signature" },
    { id: 21, title: "Maison en pierre", category: "Maison", imageUrl: "imgSheep/img21.PNG", price: 6800, quality: "best", type: "Signature" },
    { id: 22, title: "Vallée luxuriante", category: "Paysage", imageUrl: "imgSheep/img22.PNG", price: 6600, quality: "best", type: "Signature" },
    { id: 23, title: "Ambiance pub", category: "Pub", imageUrl: "imgSheep/img23.PNG", price: 6400, quality: "best", type: "Signature" },
    { id: 24, title: "Maison berbère", category: "Maison", imageUrl: "imgSheep/img24.PNG", price: 6200, quality: "best", type: "Signature" },
    { id: 25, title: "Colline en fleurs", category: "Paysage", imageUrl: "imgSheep/img25.PNG", price: 6000, quality: "best", type: "Signature" },
    { id: 26, title: "Pub rustique", category: "Pub", imageUrl: "imgSheep/img26.PNG", price: 5800, quality: "medium", type: "Essentials" },
    { id: 27, title: "Maison moderne", category: "Maison", imageUrl: "imgSheep/img27.PNG", price: 5600, quality: "medium", type: "Essentials" },
    { id: 28, title: "Route du désert", category: "Paysage", imageUrl: "imgSheep/img28.PNG", price: 5400, quality: "medium", type: "Essentials" },
    { id: 29, title: "Pub de village", category: "Pub", imageUrl: "imgSheep/img29.PNG", price: 5200, quality: "medium", type: "Essentials" },
    { id: 30, title: "Maison traditionnelle", category: "Maison", imageUrl: "imgSheep/img30.PNG", price: 5000, quality: "medium", type: "Essentials" }
  ];
  
  export default photoList;
  